### PR TITLE
Optimize lodash, TypeScript updates

### PR DESCRIPTION
**Pull request by jednano**
TypeScript has been going through a lot of changes of recent. With TypeScript 2.0.1 on the horizon, you might want these updates as well.

### CODE REVIEW

**Comment by sanemat** [comment]
+78 −9,197 :open_mouth: Update dependencies is hard, I understand.

**Comment by sanemat** [comment]
Thank you for your investigation and patches :bow:

**Comment by jednano** [comment]
The reason there were so many deletions is because TypeScript changed the way you install typings recently, making them install as node modules. Anyway, always love deleting massive amounts of code!

**Comment by jednano** [comment]
I still think we would do well to wait for the official release of TypeScript 2.0.1, which should be happening some time at the end of next week, I hope. See https://github.com/Microsoft/TypeScript/milestones

**Pull request merged**
